import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import DialogProvider from "@/providers/dialog-provider";
import { ClientSidebar } from "@/components/client-sidebar-provider";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'], // Choose the character subsets you need
  weight: ['400'], // Specify font weights
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased `}>
        <DialogProvider />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClientSidebar>
              {children}
          </ClientSidebar>
        </ThemeProvider>
      </body>
    </html>
  );
}
