import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider"
import DialogProvider from "@/providers/dialog-provider";
import { headers } from "next/headers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers(); 
  const referer = headersList.get('referer') || ''
  let currentPathname = ""
  if (referer) currentPathname = new URL(referer).pathname
  // console.log(currentPathname)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <DialogProvider />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {currentPathname !== '/login' ? <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <SidebarTrigger className="hover:bg-transparent" />
              {children}
            </SidebarInset>
          </SidebarProvider> :
            <>
              {children}
            </>
          }
        </ThemeProvider>
      </body>
    </html>
  );
}
