import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import { Open_Sans } from 'next/font/google'
import DialogProvider from "@/providers/dialog-provider";
import { Toaster } from 'sonner';
const openSans = Open_Sans({
  subsets: ['latin']
  ,
  variable: "--font-open-sans",
  weight: ["300", "800"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} min-h-screen bg-gray-900 text-white`}>
      <DialogProvider/>
          {/* Header */}
          <div className="h-[80px] fixed inset-y-0 w-full z-[100] bg-gray-900">
            <Header />
          </div>

          {/* Sidebar */}
          <div className="flex flex-col h-full">
            <div className="flex flex-1">
              <div className="hidden lg:flex pt-[80px] h-full w-72 flex-col fixed inset-y-0 z-[48] bg-white border-r border-r-gray-800 overflow-y-auto overflow-x-hidden">
                <Sidebar />
              </div>

              {/* Main Content */}
              <main className="lg:pl-72 pt-[80px] flex-1 ">
                <div className="max-w-screen-xl mx-auto p-2">
                  {/* Page Content */}
                  {children}
                  <Toaster richColors position="top-center"duration={2000}/>
                </div>
              </main>
            </div>
          </div>
      </body>
    </html>
  );
}

